---
flatpak_flathub_packages:
- org.freedesktop.Platform/x86_64/23.08
- com.github.tchx84.Flatseal
- org.signal.Signal
- com.calibre_ebook.calibre
- com.protonvpn.www
- us.zoom.Zoom
- fr.handbrake.ghb
- dev.geopjr.Tuba
- org.gnome.Maps
- org.gnome.Totem
- org.videolan.VLC
- org.gnome.Boxes
- org.gnome.Weather

homebrew_casks:
- ungoogled-chromium
- zed
- zoom

homebrew_formula:
- the_silver_searcher
- kubernetes-cli
- k9s
- kubectx
- direnv
