---
- hosts: all
  tasks:
  - debug:
      msg: "{{ vars }}"
  - name: Group all hosts by os
    group_by: key={{ ansible_os_family }}
  tags:
  - always

- name: Bootstrap
  hosts: all
  roles:
  - bootstrap
  tags:
  - bootstrap

- name: Install and configure git
  hosts: all
  roles:
  - git
  tags:
  - git

- name: Install fonts
  hosts: all
  roles:
  - fonts
  tags:
  - fonts

- name: Configure shell
  hosts: all
  roles:
  - zsh
  tags:
  - shell

- name: Configure terminal
  hosts: all
  roles:
  - term
  tags:
  - term

- name: Install and configure vim
  hosts: all
  roles:
  - vim
  tags:
  - vim

- name: Install misc packages
  hosts: all
  roles:
  - misc
  tags:
  - misc

- name: AWS stuff
  hosts: all
  roles:
  - aws
  tags:
  - aws

- name: Python stuff
  hosts: all
  roles:
  - python
  tags:
  - python

- name: Go stuff
  hosts: all
  roles:
  - golang
  tags:
  - golang
