---
- name: shim pyenv into ~/.profile
  lineinfile:
    path: "/Users/{{ ansible_user_id }}/.profile"
    line: "export PATH=${PATH}:{{ pyenv_root }}/bin"
    regexp: "^export PATH=${PATH}"

- name: Add pyenv to .profile
  lineinfile:
    dest: "/Users/{{ ansible_user_id }}/.profile"
    line: 'eval "$(pyenv init -)"'

# NOTE: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install 3.7.3
# If you're getting compilation errors caused by xcode cli tools

- name: Install pyenv release
  shell: "{{ pyenv_root }}/bin/pyenv install {{ python_version }}:latest"
  ignore_errors: true
