---
- name: create pyenv directory
  file:
    path: "{{ pyenv_root }}"
    state: directory
    force: yes

- name: clone pyenv to pyenv directory
  git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: "{{ pyenv_root }}"
    force: yes

- include_tasks: darwin.yml
  when: ansible_system == "Darwin"
