---
hashi_download_base_url: "https://releases.hashicorp.com"

# Hashi now blocks scraping their DL page, so specifying name/version pairs  here
tools:
  - name: consul
    version: 1.22.2
  - name: hcp
    version: 0.11.0
  - name: nomad
    version: 1.11.1
  - name: packer
    version: 1.14.3
  - name: sentinel
    version: 0.40.0
  - name: terraform
    version: 1.14.3
  - name: vault
    version: 1.21.1
