---
hashi_download_base_url: "https://releases.hashicorp.com"

# Hashi now blocks scraping their DL page, so specifying name/version pairs  here
tools:
  - name: consul
    version: 1.20.5
  - name: hcp
    version: 0.9.0
  - name: nomad
    version: 1.10.0
  - name: packer
    version: 1.12.0
  - name: sentinel
    version: 0.30.0
  - name: terraform
    version: 1.11.4
  - name: vault
    version: 1.19.1
