---
- name: install cli for github
  homebrew:
    name: gh
    state: latest

# http://pre-commit.com
- name: install pre-commit for git
  homebrew:
    name: pre-commit
    state: latest

# http://pre-commit.com
- name: install pre-commit for git
  homebrew:
    name: pre-commit
    state: latest
