---
- name: install cli for github
  homebrew:
    name: gh
    state: latest

# http://pre-commit.com
- name: install pre-commit for git
  homebrew:
    name: pre-commit
    state: latest

# http://pre-commit.com
- name: install pre-commit for git
  homebrew:
    name: pre-commit
    state: latest

# http://pre-commit.com
- name: install pre-commit for git
  homebrew:
    name: pre-commit
    state: latest

# Manages HTTPS-based credentials (required for many SSO orgs)
- name: install microsoft's git-credential-manager-core
  block:
    - name: tap microsoft git homebrew
      homebrew_tap:
        name: microsoft/git

    - name: install cask
      homebrew_cask:
        name: git-credential-manager
