---
- name: Install git
  package:
    name: git
    state: latest
  become: true

- name: Add github cli official GPG key
  apt_key:
    keyserver: "{{ gh_gpg_source }}"
    id: "{{ gh_gpg_key_id }}"
    state: present
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "Ubuntu")
  become: true

- name: enable github cli source in package repository
  include_role:
    name: packages
  vars:
    add_source: true
    package_source: "{{ gh_source }}"

- name: update packages
  include_role:
    name: packages
  vars:
    update_cache: true

- name: Install cli for github
  package:
    name: gh
    state: latest
  become: true

#- name: install pre-commit for git
#  pip:
#    name: pre-commit

# Note: there is an external dependency here - you must have git-credential-manager-core installed in Windows!!!
- name: alias Windows git-credential-manager into WSL environment
  copy:
    src: "{{ role_path}}/files/git-credential-manager"
    dest: /usr/bin/git-credential-manager
    owner: root
    group: root
    mode: '0755'
  when: wsl_environment
  become: true

- name: Install git-credential-manager (gcm)
  block:
  - name: check if git-credential-manager is installed
    command: "dpkg-query -W {{ gcm_deb_package_name }}"
    register: gcm_install_check
    failed_when: gcm_install_check.rc > 1
    changed_when: gcm_install_check.rc == 1

  - name: download gcm
    get_url:
      url: "{{ gcm_deb_url }}"
      dest: "{{ working_dir }}/{{ gcm_deb_package_name }}"
    when: gcm_install_check.rc == 1

  - name: install gcm
    apt: deb="{{ working_dir }}/{{ gcm_deb_package_name }}"
    when: gcm_install_check.rc == 1
    become: true
  when: wsl_environment != true

