---
- name: enable rancher in package repository
  include_role:
    name: packages
  vars:
    add_source: true
    package_source: "{{ rancher_source }}"

- name: Add rancher official GPG key
  include_role:
    name: packages
  vars:
    add_gpg: true
    gpg_source: "{{ rancher_gpg_source }}"
    gpg_key_id: "{{ rancher_gpg_key_id }}"

- name: update packages
  include_role:
    name: packages
  vars:
    update_cache: true

- name: Install rancher
  package:
    name: rancher-desktop
    state: latest
  become: true
