---
- include_tasks: linux.yml
  when: ansible_system == "Linux"

- include_tasks: darwin.yml
  when: ansible_system == "Darwin"

- name: add rd binary to PATH
  lineinfile:
    dest: "~/.zshrc"
    insertafter: BOF
    line: 'export PATH=$PATH:~/.rd/bin'
    state: present
