---
- name: autohide OSX dock
  shell: defaults write com.apple.dock autohide true
  notify: restart dock

- name: pin OSX dock to right edge
  shell: defaults write com.apple.dock orientation right
  notify: restart dock

- name: check if privileges cli app is installed (corporate nanny)
  command: /Applications/Privileges.app/Contents/Resources/PrivilegesCLI --help
  register: privs_install_check
  ignore_errors: yes

- name: add privileges app alias
  lineinfile:
    dest: "~/.zshrc"
    line : alias privs=/Applications/Privileges.app/Contents/Resources/PrivilegesCLI
  when: privs_install_check.rc == 0
