---
- name: Install lshw
  package:
    name: lshw
    state: latest
  when: wsl_environment == false

- name: Install kupfer
  package:
    name: kupfer
    state: latest
  when: wsl_environment == false
