---
- name: Install lshw
  package:
    name: lshw
    state: latest
  when: wsl_environment == false

- name: Install kupfer
  package:
    name: kupfer
    state: latest
  when: wsl_environment == false

- name: Install direnv
  package:
    name: direnv
    state: latest
  become: true

- name: Install tree
  package:
    name: tree
    state: latest
  become: true
