---
- name: Install lshw
  package:
    name: lshw
    state: latest
  when: wsl_environment == false
  become: true

- name: Install direnv
  package:
    name: direnv
    state: latest
  become: true

- name: Install pass
  package:
    name: pass
    state: latest
  become: true

- name: Install libdvdcss
  package:
    name: libdvd-pkg
    state: latest
  become: true

- name: Install gstreamer packages
  package:
    name: "gstreamer1.0-plugins-{{ item }}"
    state: latest
  loop:
    - "bad"
    - "ugly"
  become: true
