---
- name: Install lshw
  package:
    name: lshw
    state: latest
  when: wsl_environment == false
  become: true

- name: Install direnv
  package:
    name: direnv
    state: latest
  become: true

- name: Install pass
  package:
    name: pass
    state: latest
  become: true
